name: Scrape, classify, evaluate

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          cache-dependency-glob: "scrape_dafont.py"

      - name: Scrape
        run: uv run scrape_dafont.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add tasks.json last_scraped_at.txt
          git commit -m "Update tasks and last_scraped_at [auto]" || echo "No changes to commit"
          git push

      - name: Classify tasks
        run: uv run ask_llms.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LLM_GEMINI_KEY: ${{ secrets.LLM_GEMINI_KEY }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add guesses.json
          git commit -m "Classify tasks [auto]" || echo "No changes to commit"
          git push

      - name: Evaluate
        run: uv run evaluate.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "Evaluate guesses [auto]" || echo "No changes to commit"
          git push
